version: 3.9

services:
  frontend_cellular_automata:
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/app

    ports:
      - 127.0.0.1:3000:3000

    command: yarn dev --host --port 3000